###################################################################
#		市街地火災シミュレーションVersion2条件設定ファイル
#			平成２０年１１月
###################################################################

###################################################################
#	共通パラメータ設定
###################################################################
[MAIN]
# 処理実行フラグ：0 データコンバータ；1 延焼シミュレーション
exeStep = 0

# ログファイル
LogFile = .\simfire.log

###################################################################
#	データコンバータ　パラメータ設定
###################################################################

[Generator]
InPath = ..\GeneFile\gene_out
OutPath = .

#入力データのsimfireバージョン
dataVersion = 2

# 入力用建物データファイル名
inBuildFile = smfrdat.txt

# 入力用建物内部データファイル名
inRoomFile = 

#AttributeList = 

# 入力用塀柵樹木データファイル名
inHedgeFile = 

# 出力用メッシュデータファイル名
outMeshFile = 

# 出力用建物データファイル名
outBuildFile = builds.dat

# 出力用建物内部データファイル名
outRoomFile = rooms.dat

# 出力用塀柵樹木データファイル名
outHedgeFile = 

# 構造定義テーブルファイル名
KozoConvertTable = stdKOZOtable.csv

# 用途定義テーブルファイル名
YotoConvertTable = stdYOTOtable.csv

# メッシュサイズ
MeshSize = 1000

# 内部メッシュの最低サイズ
#minInnerMeshSize = 50

#高さ情報生成フラグ
heightFlg = 0

#付属面情報生成フラグ
roofFlg = 0

#開口部自動生成フラグ：0 なし；>0 あり
opFlg = 3

#開口部の構造指定モード：0:標準（材質IDが0の時open0、非0の時open1）,　>0:直接指定（材質IDを直接面材参照番号として採用）
opMaterialMode = 0

#自動分割フラグ：0 なし；>0 あり
divFlg = 0

# 分割する最低面積（平方メートル）
arealmit = 10

# 分割する最大面積（平方メートル）
areaMax = 200

# 区画分割する時に無視する角度範囲（度）
defaultAngle = 200

# 区画分割する時に無視する長さ範囲（メートル）
defaultDist = 3

# 区画分割する時に無視するアスペクト比
defaultAspect = 1.5

#対面距離別開口率
opRatio0 = 0, 0.2, 0.2, 0.5, 0.5

#開口部種別を防火設備とする最大隣接間隔（開口部種別を0以外とした構造種別の区画のみに有効）
fireDoorDist = 6, 10
