<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AnalysisLevel>none</AnalysisLevel>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3351.48" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimulationCommonLibrary\SimulationCommonLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\images\firepoint_icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\images\wind_direction_arrow.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\images\firepoint.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\legend_icon.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\spritesheet-2x.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\images\spritesheet.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\building.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\firePoint.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\map.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\map.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\map.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\tertiaryMesh.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- ここから↓↓ 他のプロジェクトの実行exeを実行フォルダに複製して配置 -->
  <Target Name="CopyFromOtherProject" AfterTargets="Build">
    <ItemGroup>
      <ExeFiles Include="..\SimulationResultFileConverter\bin\$(Configuration)\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(ExeFiles)" DestinationFolder="$(OutputPath)\ResultFileConv" SkipUnchangedFiles="true" />
  </Target>
  <!-- ここまで↑↑ -->

  <!-- ここから↓↓ 外部ツールを実行フォルダに複製して配置 -->
  <Target Name="CopyFromExternalTools" AfterTargets="Build">
    <ItemGroup>
      <SimFire Include="..\ExternalTools\SimFire_ForSupportTool\\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(SimFire)" DestinationFolder="$(OutputPath)\SimFire\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>
  <!-- ここまで↑↑ -->

</Project>
