<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="DotSpatial.Projections" Version="4.0.656" />
    <PackageReference Include="GeoJSON" Version="2.3.1" />
    <PackageReference Include="log4net" Version="3.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118" />
  </ItemGroup>

</Project>
